### ISSUE TITLE
移动端1px的线

### ISSUE THREAD

**Issue by russellmars** [russellmars/blog#2]
在移动端布局的时候，边框明明是写的1px为什么看起来会变粗呢，实际上这个和设备像素比（devicePixelRatio）有关，在dpr大于1的时候，一个css像素会显示多个实际设备像素导致的。

我这里总结了几个常见的1px细线解决方案。

## 直接用小数写边框
``` css
.border { border: 1px solid #999 }
@media screen and (-webkit-min-device-pixel-ratio: 2) {
    .border { border: 0.5px solid #999 }
}
@media screen and (-webkit-min-device-pixel-ratio: 3) {
    .border { border: 0.333333px solid #999 }
}
```

优点：简单
缺点：android和低版本的ios不支持

## transform + 伪类实现
``` less
.box {
  position: relative;
  height: 100px;
  width: 100px;
  transform-style: preserve-3d;  /* 防止有些时候会不显示边框 */
  &::before{
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 200%;
    height: 200%;
    border:1px solid red;
    transform-origin: left top;
    transform: scale(0.5);
    box-sizing: border-box;
    z-index: -1;   /* 防止点击触发, 放在下层 */
    pointer-events: none;
    @media screen and (min-device-pixel-ratio:3),(-webkit-min-device-pixel-ratio:3){
      width: 300%;
      height: 300%;
      transform: scale(0.33);
    }
  }
}
```

优点： 兼容性好，同理还可以实现带圆角的4上下左右四条边框
缺点： 占用了before，after伪元素，容易冲突，input，和button等元素没有before，after伪元素需注意，最多用div再包一层
